### ISSUE TITLE
Blender 4.2.0 compatibility?

### ISSUE THREAD

**Issue by Adythlay** [hannesdelbeke/mesh-data-transfer#3]
Hi Maurizio, first of all, thank you for working so hard on this addon and for sharing it, works great with the previous versions of Blender. 

But, I get this error when installing the latest version;

Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 1302, in execute
    cmd_batch = self.exec_command_iter(is_modal)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2338, in exec_command_iter
    self.exec_legacy(source_filepath)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2465, in exec_legacy
    bpy.types.PREFERENCES_OT_addon_install.execute(self, bpy.context)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\startup\bl_operators\userpref.py", line 780, in execute
    bpy.ops.preferences.addon_enable(module=mod.__name__)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: No module named 'mesh-data-transfer-2'

**Comment by hannesdelbeke** [comment]
Did you perhaps rename or duplicate this file by accident?

It seems to be named `mesh-data-transfer-2` instead of `mesh-data-transfer` in your error message.

Try removing all related files and carefully reinstalling the addon.
